# Generated by Django 5.2 on 2025-04-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.CharField(help_text='User ID', max_length=20)),
                ('User_Name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('No_of_seats', models.IntegerField()),
                ('Movie_Name', models.CharField(max_length=20)),
                ('Show_DateTime', models.DateTimeField()),
                ('Phone_Number', models.CharField(help_text='Phone number', max_length=10)),
            ],
        ),
    ]
